---
title: "paper"
format: html
---

# Background
```{r}
#| echo: false

#calling libraries
library(tidyverse)
library(here)
library(janitor)
library(lubridate)
library(patchwork)
library(zoo)

#sourcing the moving average function for analysis of the data 
source(here("R", "moving-average-function.R"))
```


# Data
```{r}
#read in data
bq1_data <- read_csv(here::here("data", "QuebradaCuenca1-Bisley.csv")) |> 
  clean_names() |> 
  select(sample_id, sample_date, k, no3_n, mg, ca, nh4_n)

bq2_data <- read_csv(here::here("data", "QuebradaCuenca2-Bisley.csv")) |> 
  clean_names() |> 
  select(sample_id, sample_date, k, no3_n, mg, ca, nh4_n)

bq3_data <- read_csv(here::here("data", "QuebradaCuenca3-Bisley.csv")) |> 
  clean_names() |> 
  select(sample_id, sample_date, k, no3_n, mg, ca, nh4_n)

prm_data <- read_csv(here::here("data", "RioMameyesPuenteRoto.csv")) |> 
  clean_names() |> 
  select(sample_id, sample_date, k, no3_n, mg, ca, nh4_n)

#join data frames
compiled_data <- rbind(bq1_data, bq2_data, bq3_data, prm_data)

#clean names for easier reference to names
compiled_data <- compiled_data |> clean_names()

#filter data for necessary columns 
compiled_data <- compiled_data |> 
  select(sample_id, sample_date, k, no3_n, mg, ca, nh4_n) |> 
  filter(sample_date >= "1988-01-05",
         sample_date <= "1994-12-27")
```

# Methods
```{r}
#calculating 9 day moving average using mutate and group by 
mov_avg_k <- compiled_data |> 
  group_by(sample_id) |> #group by sample sites
  #mutating to create a new column
  mutate(mov_avg_k = sapply(sample_date, #sapply to run on all of the data 
                            moving_average, 
                            sample_date = sample_date, 
                            nutrient_conc = k, 
                            win_size_wks = 9)) |> 
  #selecting for just necessary data to create a plot 
  select(sample_id, sample_date, k, mov_avg_k)

#calculating 9 day moving average using mutate and group by 
mov_avg_mg <- compiled_data |> 
  group_by(sample_id) |> #group by sample sites
  #mutating to create a new column
  mutate(mov_avg_mg = sapply(sample_date, #sapply to run on all of the data 
                            moving_average, 
                            sample_date = sample_date, 
                            nutrient_conc = mg, 
                            win_size_wks = 9)) |> 
  #selecting for just necessary data to create a plot 
  select(sample_id, sample_date, mg, mov_avg_mg)

#calculating 9 day moving average using mutate and group by 
mov_avg_no3_n <- compiled_data |> 
  group_by(sample_id) |> #group by sample sites
  #mutating to create a new column
  mutate(mov_avg_no3_n = sapply(sample_date, #sapply to run on all of the data 
                            moving_average, 
                            sample_date = sample_date, 
                            nutrient_conc = no3_n, 
                            win_size_wks = 9)) |> 
  #selecting for just necessary data to create a plot 
  select(sample_id, sample_date, no3_n, mov_avg_no3_n)

#calculating 9 day moving average using mutate and group by 
mov_avg_ca <- compiled_data |> 
  group_by(sample_id) |> #group by sample sites
  #mutating to create a new column
  mutate(mov_avg_ca = sapply(sample_date, #sapply to run on all of the data 
                            moving_average, 
                            sample_date = sample_date, 
                            nutrient_conc = ca, 
                            win_size_wks = 9)) |> 
  #selecting for just necessary data to create a plot 
  select(sample_id, sample_date, ca, mov_avg_ca)

#calculating 9 day moving average using mutate and group by 
mov_avg_nh4_n <- compiled_data |> 
  group_by(sample_id) |> #group by sample sites
  #mutating to create a new column
  mutate(mov_avg_nh4_n = sapply(sample_date, #sapply to run on all of the data 
                            moving_average, 
                            sample_date = sample_date, 
                            nutrient_conc = nh4_n, 
                            win_size_wks = 9)) |> 
  #selecting for just necessary data to create a plot 
  select(sample_id, sample_date, nh4_n, mov_avg_nh4_n)
```

# Results
```{r}
#creating a hurricane line
hurricane <- as.Date("1989-09-18")

# ggplot of the rollmean average k 
k_plot <- ggplot(data = mov_avg_k, aes(x = sample_date, y = mov_avg_k, linetype = sample_id)) +
  geom_line() +
  geom_vline(xintercept = hurricane, linetype = "dashed") +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank()) +
  labs(y = "K mg |-1")

# ggplot of the rollmean average NO3_N
no3_n_plot <- ggplot(data = mov_avg_no3_n, aes(x = sample_date, y = mov_avg_no3_n, linetype = sample_id)) +
  geom_line() +
  geom_vline(xintercept = hurricane, linetype = "dashed") +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank()) +
  labs(y = "NO3-N ug |-1")

# ggplot of the rollmean average NO3_N
mg_plot <- ggplot(data = mov_avg_mg, aes(x = sample_date, y = mov_avg_mg, linetype = sample_id)) +
  geom_line() +
  geom_vline(xintercept = hurricane, linetype = "dashed") +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank()) +
  labs(y = "Mg mg |-1")

# ggplot of the rollmean average NO3_N
ca_plot <- ggplot(data = mov_avg_ca, aes(x = sample_date, y = mov_avg_ca, linetype = sample_id)) +
  geom_line() +
  geom_vline(xintercept = hurricane, linetype = "dashed") +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank()) +
  labs(y = "Ca mg |-1")

# ggplot of the rollmean average NH4_N
nh4_n_plot <- ggplot(data = mov_avg_nh4_n, aes(x = sample_date, y = mov_avg_nh4_n, linetype = sample_id)) +
  geom_line() +
  geom_vline(xintercept = hurricane, linetype = "dashed") +
  labs(x = "Years",
       y = "NH4-N ug |-1")

k_plot / no3_n_plot / mg_plot / ca_plot / nh4_n_plot +
  plot_layout(guides = 'collect')

```

Figure 3. Concentrations in Bisley, Puerto Rico streams before and after Hurricane Hugo, 9-wk moving
averages. (a) potassium, (b) nitrate-N, (c) magnesium, (d) calcium and (e) ammonium-N. The vertical lines
mark the time of hurricane disturbance.